TRUNCATE TABLE vehicle_master;
INSERT INTO vehicle_master (make, model, variant) VALUES
('Tata','Nano Genx','Xt'),
('Tata','Nano Genx','Xe'),
('Tata','Nano Genx','Emax Xm'),
('Tata','Nano Genx','Xta'),
('Tata','Nano Genx','Xm'),
('Tata','Nano Genx','Xma'),
('Datsun','Redi-Go','D'),
('Datsun','Redi-Go','T'),
('Datsun','Redi-Go','A'),
('Datsun','Redi-Go','S'),
('Datsun','Redi-Go','1.0 S'),
('Datsun','Redi-Go','1.0 S Amt'),
('Renault','Kwid','Rxe 0.8'),
('Renault','Kwid','Std 0.8'),
('Renault','Kwid','Rxl 0.8'),
('Renault','Kwid','Rxt 0.8'),
('Renault','Kwid','Rxt 1.0'),
('Renault','Kwid','Climber 1.0 Mt'),
('Renault','Kwid','Rxt Amt 1.0'),
('Renault','Kwid','Climber Amt 1.0'),
('Renault','Kwid','Rxt (O) 1.0'),
('Renault','Kwid','Rxt (O) Amt 1.0'),
('Renault','Kwid','Climber (O) Mt 1.0'),
('Renault','Kwid','Climber (O) Amt 1.0'),
('Maruti Suzuki','Eeco','5 Str'),
('Maruti Suzuki','Eeco','7 Str'),
('Maruti Suzuki','Eeco','5 Str With Ac+Htr'),
('Maruti Suzuki','Eeco','5 Str With Ac+Htr Cng'),
('Maruti Suzuki','Eeco','5 Str With Htr Cng'),
('Maruti Suzuki','Alto K10','Lxi'),
('Maruti Suzuki','Alto K10','Vxi'),
('Maruti Suzuki','Alto K10','Lx'),
('Maruti Suzuki','Alto K10','Vxi (O)'),
('Maruti Suzuki','Alto K10','Lxi Cng (O)'),
('Maruti Suzuki','Alto K10','Vxi Amt (O)'),
('Datsun','Go','D'),
('Datsun','Go','T'),
('Datsun','Go','T (O)'),
('Datsun','Go','A (O)'),
('Datsun','Go','A'),
('Datsun','Go','T Vdc'),
('Datsun','Go','T (O) Vdc'),
('Datsun','Go','T Cvt'),
('Datsun','Go','T (O) Cvt'),
('Maruti Suzuki','Celerio Tour','H2'),
('Maruti Suzuki','Celerio Tour','H2 Cng'),
('Hyundai','Santro','Era Mt'),
('Hyundai','Santro','Magna Mt'),
('Hyundai','Santro','Magna Mt Cng'),
('Hyundai','Santro','Magna Amt'),
('Hyundai','Santro','Sportz Mt'),
('Hyundai','Santro','Sportz Mt Cng'),
('Hyundai','Santro','Sportz Amt'),
('Hyundai','Santro','Asta Mt'),
('Tata','Tiago','Revotron Xe'),
('Tata','Tiago','Revotron Xt'),
('Tata','Tiago','Revotron Xz'),
('Tata','Tiago','Revotron Xz Plus'),
('Tata','Tiago','Revotron Xz Plus Dual Tone'),
('Tata','Tiago','Revotron Xza'),
('Tata','Tiago','Revotron Xza Plus'),
('Tata','Tiago','Revotron Xza Plus Dual Tone'),
('Maruti Suzuki','Celerio X','Vxi (O)'),
('Maruti Suzuki','Celerio X','Vxi'),
('Maruti Suzuki','Celerio X','Vxi Amt'),
('Maruti Suzuki','Celerio X','Vxi Amt (O)'),
('Maruti Suzuki','Celerio X','Zxi'),
('Maruti Suzuki','Celerio X','Zxi (O)'),
('Maruti Suzuki','Celerio X','Zxi Amt'),
('Maruti Suzuki','Celerio X','Zxi Amt (O)'),
('Maruti Suzuki','Ignis','Alpha 1.2 Amt'),
('Maruti Suzuki','Ignis','Alpha 1.2 Mt'),
('Maruti Suzuki','Ignis','Delta 1.2 Amt'),
('Maruti Suzuki','Ignis','Delta 1.2 Mt'),
('Maruti Suzuki','Ignis','Sigma 1.2 Mt'),
('Maruti Suzuki','Ignis','Zeta 1.2 Amt'),
('Maruti Suzuki','Ignis','Zeta 1.2 Mt'),
('Renault','Triber','Rxe'),
('Renault','Triber','Rxl'),
('Renault','Triber','Rxt'),
('Renault','Triber','Rxz'),
('Premier','Rio','Gx'),
('Premier','Rio','Ex'),
('Premier','Rio','Glx'),
('Premier','Rio','Dx'),
('Premier','Rio','Lx'),
('Premier','Rio','Crdi4'),
('Toyota','Etios Liva','G'),
('Toyota','Etios Liva','V'),
('Toyota','Etios Liva','Gd'),
('Toyota','Etios Liva','Vx'),
('Toyota','Etios Liva','Vxd'),
('Toyota','Etios Liva','Vd'),
('Toyota','Etios Liva','Dual Tone V'),
('Toyota','Etios Liva','Dual Tone Vd'),
('Toyota','Etios Liva','Dual Tone Vx'),
('Toyota','Etios Liva','Dual Tone Vxd'),
('Toyota','Etios Liva','Gx'),
('Toyota','Etios Liva','Gxd'),
('Toyota','Etios Liva','Vx Dual Tone Limited Edition'),
('Toyota','Etios Liva','Vxd Dual Tone Limited Edition'),
('Nissan','Micra Active','Xl'),
('Nissan','Micra Active','Xv'),
('Nissan','Micra Active','Xl (O)'),
('Tata','Bolt','Xt Diesel'),
('Tata','Bolt','Xe Diesel'),
('Tata','Bolt','Xm Diesel'),
('Tata','Bolt','Xms Diesel'),
('Tata','Bolt','Xt Petrol'),
('Tata','Bolt','Xe Petrol'),
('Tata','Bolt','Xm Petrol'),
('Tata','Bolt','Xms Petrol'),
('Hyundai','Xcent Prime','Cng T + (Cng +'),
('Hyundai','Xcent Prime','T'),
('Hyundai','Xcent Prime','T+'),
('Hyundai','Xcent Prime','Cng T (Cng +'),
('Hyundai','Xcent Prime','T+ Crdi'),
('Hyundai','Xcent Prime','T Crdi'),
('Maruti Suzuki','Dzire Tour','Ldi'),
('Maruti Suzuki','Dzire Tour','Lxi'),
('Maruti Suzuki','Dzire Tour','Lxi Cng'),
('Hyundai','Elite I20','Era 1.2'),
('Hyundai','Elite I20','Era 1.4 Crdi'),
('Hyundai','Elite I20','Magna Plus'),
('Hyundai','Elite I20','Magna Plus Crdi'),
('Hyundai','Elite I20','Sportz Plus'),
('Hyundai','Elite I20','Sportz Plus Crdi Dual Tone'),
('Hyundai','Elite I20','Asta (O) 1.2'),
('Hyundai','Elite I20','Asta (O) Crdi'),
('Hyundai','Elite I20','Asta (O) Cvt'),
('Hyundai','Elite I20','Sportz Plus Dual Tone'),
('Hyundai','Elite I20','Sportz Plus Cvt'),
('Hyundai','Elite I20','Sportz Plus Crdi'),
('Hyundai','Aura','E 1.2 Petrol'),
('Hyundai','Aura','S 1.2 Petrol'),
('Hyundai','Aura','S 1.2 Amt Petrol'),
('Hyundai','Aura','Sx 1.2 Petrol'),
('Hyundai','Aura','Sx Plus 1.2 Amt Petrol'),
('Hyundai','Aura','Sx (O) 1.2 Petrol'),
('Hyundai','Aura','S 1.2 Cng Petrol (Cng +'),
('Hyundai','Aura','Sx Plus 1.0 Petrol'),
('Hyundai','Aura','S 1.2 Diesel'),
('Hyundai','Aura','S 1.2 Amt Diesel'),
('Hyundai','Aura','Sx Plus 1.2 Amt Diesel'),
('Hyundai','Aura','Sx (O) 1.2 Diesel'),
('Volkswagen','Polo','Trendline 1.0L (P)'),
('Volkswagen','Polo','Comfortline 1.0 (P)'),
('Volkswagen','Polo','Highline Plus 1.0 (P)'),
('Volkswagen','Polo','Trendline 1.5L (D)'),
('Volkswagen','Polo','Comfortline 1.5 (D)'),
('Volkswagen','Polo','Highline Plus 1.5 (D)'),
('Volkswagen','Polo','Gt Tsi'),
('Volkswagen','Polo','Gt Tdi'),
('Maruti Suzuki','Dzire','Lxi'),
('Maruti Suzuki','Dzire','Vxi'),
('Maruti Suzuki','Dzire','Ldi'),
('Maruti Suzuki','Dzire','Zxi'),
('Maruti Suzuki','Dzire','Vdi'),
('Maruti Suzuki','Dzire','Vxi Amt'),
('Maruti Suzuki','Dzire','Zdi Amt'),
('Maruti Suzuki','Dzire','Zdi'),
('Maruti Suzuki','Dzire','Zxi Plus'),
('Maruti Suzuki','Dzire','Zxi At'),
('Maruti Suzuki','Dzire','Zxi Plus Amt'),
('Maruti Suzuki','Dzire','Zdi Plus'),
('Maruti Suzuki','Dzire','Vdi Amt'),
('Maruti Suzuki','Dzire','Zdi Plus Amt'),
('Ford','Freestyle','1.5L Tdci Ambiente'),
('Ford','Freestyle','1.5L Tdci Titanium'),
('Ford','Freestyle','1.5L Tdci Titanium Plus'),
('Ford','Freestyle','1.2L Ti-Vct Ambiente'),
('Ford','Freestyle','1.2L Ti-Vct Titanium'),
('Ford','Freestyle','1.2L Ti-Vct Titanium Plus'),
('Ford','Freestyle','1.2L Ti-Vct Trend Plus'),
('Ford','Freestyle','1.5L Tdci Trend Plus'),
('Volkswagen','Ameo','Trendline 1.5L Tdi'),
('Volkswagen','Ameo','Comfortline 1.5L Tdi'),
('Volkswagen','Ameo','Highline Plus 1.5L Tdi Dsg'),
('Volkswagen','Ameo','Highline Plus 1.5L Tdi'),
('Volkswagen','Ameo','Trendline 1.0L'),
('Volkswagen','Ameo','Comfortline 1.0L'),
('Volkswagen','Ameo','Highline Plus 1.0L'),
('Volkswagen','Ameo','Gt Line Tdi Dsg'),
('Ford','Aspire','1.2 Ti-Vct Ambiente'),
('Ford','Aspire','1.2 Ti-Vct Trend Plus'),
('Ford','Aspire','1.2 Ti-Vct Trend'),
('Ford','Aspire','1.5 Tdci Ambiente'),
('Ford','Aspire','1.5 Tdci Trend'),
('Ford','Aspire','1.5 Tdci Trend Plus'),
('Ford','Aspire','1.5 Tdci Titanium'),
('Ford','Aspire','1.5 Tdci Titanium Plus'),
('Ford','Aspire','1.2 Ti-Vct Titanium Plus'),
('Ford','Aspire','1.2 Ti-Vct Titanium'),
('Ford','Aspire','1.2 Trend Plus Cng'),
('Ford','Aspire','1.2 Ti-Vct Blu'),
('Ford','Aspire','1.5 Tdci Blu'),
('Toyota','Platinum Etios','G'),
('Toyota','Platinum Etios','V'),
('Toyota','Platinum Etios','Gd'),
('Toyota','Platinum Etios','Vd'),
('Toyota','Platinum Etios','Vxd'),
('Toyota','Platinum Etios','Vx'),
('Toyota','Platinum Etios','Gx'),
('Toyota','Platinum Etios','Gxd'),
('Toyota','Platinum Etios','Vxd Limited Edition'),
('Toyota','Platinum Etios','Vx Limited Edition'),
('Toyota','Etios Cross','V'),
('Toyota','Etios Cross','G'),
('Toyota','Etios Cross','Vd'),
('Toyota','Etios Cross','Gd'),
('Toyota','Etios Cross','1.2 X Edition'),
('Toyota','Etios Cross','1.4 X Edition'),
('Mahindra','Verito Vibe','D2'),
('Mahindra','Verito Vibe','D4'),
('Mahindra','Verito Vibe','D6'),
('Fiat','Urban Cross','1.3 Multijet Active'),
('Fiat','Urban Cross','1.3 Multijet Dynamic'),
('Fiat','Urban Cross','1.4 T-Jet Emotion'),
('Fiat','Urban Cross','1.3 Multijet Emotion'),
('Toyota','Glanza','G Hybrid'),
('Toyota','Glanza','V'),
('Toyota','Glanza','G Cvt'),
('Toyota','Glanza','V Cvt'),
('Toyota','Glanza','G Mt'),
('Fiat','Avventura','Multijet Dynamic'),
('Fiat','Avventura','Multijet Active'),
('Fiat','Avventura','Multijet Emotion'),
('Honda','Jazz','V Petrol'),
('Honda','Jazz','Vx Cvt'),
('Honda','Jazz','Vx Petrol'),
('Honda','Jazz','V Cvt'),
('Honda','Jazz','S Diesel'),
('Honda','Jazz','V Diesel'),
('Honda','Jazz','Vx Diesel'),
('Honda','Jazz','Exclusive Edition Cvt'),
('Jeep','Compass Trailhawk','2.0 Trailhawk 4X4 At'),
('Jeep','Compass Trailhawk','2.0 Trailhawk (O) 4X4 At'),
('Isuzu','Mu-X','4X2'),
('Isuzu','Mu-X','4X4'),
('Mahindra','Alturas G4','2Wd At'),
('Mahindra','Alturas G4','4Wd At'),
('Volkswagen','Tiguan','Comfortline 2.0L Tdi Amt'),
('Volkswagen','Tiguan','Highline 2.0L Tdi Amt'),
('Honda','Cr-V','2Wd Petrol Cvt'),
('Honda','Cr-V','2Wd Diesel At'),
('Honda','Cr-V','Awd Diesel At'),
('Skoda','Superb Sportline','Sportline 1.8L Tsi At'),
('Skoda','Superb Sportline','Sportline 2.0L Tdi At'),
('Audi','A3','35 Tdi Premium Plus'),
('Audi','A3','35 Tdi Technology'),
('Audi','A3','35 Tfsi Premium Plus'),
('Audi','A3','35 Tfsi Technology'),
('Skoda','Kodiaq','Style 2.0 Tdi 4X4 At'),
('Skoda','Kodiaq','Laurin And Klement'),
('Skoda','Kodiaq','Corporate Edition'),
('DC','Avanti','Standard'),
('Audi','Q3','30 Tdi Premium Fwd'),
('Audi','Q3','35 Tdi Quattro Premium Plus'),
('Audi','Q3','35 Tdi Quattro Technology'),
('Audi','Q3','30 Tfsi Premium'),
('Mini','Cooper 5 Door','Cooper D'),
('Mini','Convertible','Cooper S'),
('Volvo','Xc40','D4 Momentum'),
('Volvo','Xc40','D4 Inscription'),
('Volvo','Xc40','T4 R-Design'),
('Mini','Clubman','Cooper S'),
('Audi','A4','Premium Plus 35 Tfsi'),
('Audi','A4','Technology 35 Tfsi'),
('Mini','John Cooper Works','Hatch'),
('Jaguar','Xe','S Petrol'),
('Jaguar','Xe','S Diesel'),
('Jaguar','Xe','Se Diesel'),
('Jaguar','Xe','Se Petrol'),
('Jaguar','Xf','2.0 Prestige'),
('Jaguar','Xf','2.0 Portfolio'),
('Jaguar','Xf','2.0 Portfolio Diesel'),
('Jaguar','Xf','2.0 Prestige Diesel'),
('Jaguar','Xf','2.0 Pure Diesel'),
('Audi','A3 Cabriolet','40 Tfsi'),
('Audi','A6','Premium Plus 45 Tfsi'),
('Audi','A6','Technology 45 Tfsi'),
('BMW','X3','Xdrive 20D Luxury Line'),
('BMW','X3','Xdrive 30I Luxury Line'),
('BMW','X3','Xdrive20D Xline'),
('Land Rover','Discovery Sport','S'),
('Land Rover','Discovery Sport','R-Dynamic Se'),
('Volvo','S90','D4 Inscription'),
('Audi','S5','Sportback'),
('BMW','X5','Xdrive30D Sport'),
('BMW','X5','Xdrive30D Xline'),
('BMW','X5','Xdrive40I M Sport'),
('Ford','Mustang','Fastback V8'),
('Jeep','Grand Cherokee','Limited'),
('Jeep','Grand Cherokee','Summit'),
('Jeep','Grand Cherokee','Srt'),
('Jeep','Grand Cherokee','Summit Petrol'),
('BMW','M2 Competition','Coupe'),
('Porsche','718','Boxster'),
('Porsche','718','Cayman'),
('Toyota','Land Cruiser Prado','Vx L'),
('Lexus','Rx 450H','450Hl Luxury'),
('Audi','Rs5','Coupe'),
('BMW','7-Series','730Ld Design Pure Excellence'),
('BMW','7-Series','730Ld Design Pure Excellence Signature'),
('BMW','7-Series','730Ld M Sport'),
('BMW','7-Series','740Li Design Pure Excellence Signature'),
('BMW','7-Series','745Le Xdrive'),
('BMW','7-Series','M760Li Xdrive'),
('Audi','Q8','55 Tfsi Quattro Tiptronic'),
('Maserati','Levante','Diesel'),
('Maserati','Levante','Gransport'),
('Maserati','Levante','Granlusson'),
('Audi','A8 L','55 Tfsi Quattro'),
('Maserati','Granturismo','Sport'),
('Maserati','Quattroporte','Granlusso'),
('Lexus','Lc 500H','Coupe'),
('Porsche','Panamera','Turbo'),
('Porsche','Panamera','Turbo Executive'),
('Porsche','Panamera','Turbo Sport Turismo'),
('Lexus','Lx 450D','V8'),
('Audi','R8','V10 Plus'),
('Lamborghini','Urus','V8'),
('Bentley','Continental Gt','Coupe'),
('Ferrari','Portofino','V8 Convertible'),
('Bentley','Bentayga','W12'),
('Bentley','Bentayga','V8'),
('Aston Martin','Db 11','V12'),
('Ferrari','458 Speciale','Coupe'),
('Bentley','Mulsanne','Sedan'),
('Bugatti','Chiron','W16'),
('Bugatti','Chiron','Sport'),
('Bajaj','Qute (Re60)','Qcar'),
('Bajaj','Qute (Re60)','Qcar Cng'),
('Maruti Suzuki','Alto','Std'),
('Maruti Suzuki','Alto','Std (O)'),
('Maruti Suzuki','Alto','Lxi'),
('Maruti Suzuki','Alto','Lxi (O)'),
('Maruti Suzuki','Alto','Vxi'),
('Maruti Suzuki','Alto','Lxi Cng (Cng +'),
('Maruti Suzuki','Alto','Lxi (O) Cng (Cng +'),
('Maruti Suzuki','Alto','Vxi Plus'),
('Maruti Suzuki','S-Presso','Std'),
('Maruti Suzuki','S-Presso','Std (O)'),
('Maruti Suzuki','S-Presso','Lxi'),
('Maruti Suzuki','S-Presso','Lxi (O)'),
('Maruti Suzuki','S-Presso','Vxi'),
('Maruti Suzuki','S-Presso','Vxi (O)'),
('Maruti Suzuki','S-Presso','Vxi Ags'),
('Maruti Suzuki','S-Presso','Vxi+'),
('Maruti Suzuki','S-Presso','Vxi (O) Ags'),
('Maruti Suzuki','S-Presso','Vxi+ Ags'),
('Maruti Suzuki','Celerio','Lxi'),
('Maruti Suzuki','Celerio','Vxi'),
('Maruti Suzuki','Celerio','Vxi At'),
('Maruti Suzuki','Celerio','Zxi'),
('Maruti Suzuki','Celerio','Zxi (Opt)'),
('Maruti Suzuki','Celerio','Vxi Cng Mt'),
('Maruti Suzuki','Celerio','Zxi Ags'),
('Maruti Suzuki','Celerio','Lxi Mt (O)'),
('Maruti Suzuki','Celerio','Vxi (O) Mt'),
('Maruti Suzuki','Celerio','Vxi (O) Ags'),
('Maruti Suzuki','Celerio','Zxi (O) Ags'),
('Hyundai','Grand I10 Prime','Era T Crdi'),
('Hyundai','Grand I10 Prime','Era T+ Crdi'),
('Hyundai','Grand I10 Prime','Era T Vtvt'),
('Hyundai','Grand I10 Prime','Era T+ Vtvt'),
('Hyundai','Grand I10 Prime','Era T+ Cng Vtvt'),
('Hyundai','Grand I10 Prime','Era T Cng Vtvt'),
('Mahindra','Kuv100 Nxt','K2 6Str'),
('Mahindra','Kuv100 Nxt','K2+ 6Str'),
('Mahindra','Kuv100 Nxt','K2 D 6Str'),
('Mahindra','Kuv100 Nxt','K2+ D 6Str'),
('Mahindra','Kuv100 Nxt','K4+ D 6Str'),
('Mahindra','Kuv100 Nxt','K4+ 6Str'),
('Mahindra','Kuv100 Nxt','K6+ 6Str'),
('Mahindra','Kuv100 Nxt','K6+ D 6Str'),
('Mahindra','Kuv100 Nxt','K8 6Str'),
('Mahindra','Kuv100 Nxt','K8 D 6Str'),
('Mahindra','Kuv100 Nxt','K8 6 Str Dual Tone'),
('Mahindra','Kuv100 Nxt','K8 D 6 Str Dual Tone'),
('Mahindra','Kuv100 Nxt','K4+ 5Str'),
('Mahindra','Kuv100 Nxt','K6+ 5Str'),
('Mahindra','Kuv100 Nxt','K8 5Str'),
('Mahindra','Kuv100 Nxt','K4+ D 5Str'),
('Mahindra','Kuv100 Nxt','K6+ D 5Str'),
('Mahindra','Kuv100 Nxt','K8 D 5Str'),
('Mahindra','Kuv100 Nxt','K2 D 5Str Taxi'),
('Mahindra','Kuv100 Nxt','K2 D 6Str Taxi'),
('Mahindra','Kuv100 Nxt','K2 5Str Cng Taxi'),
('Mahindra','Kuv100 Nxt','K2 6Str Cng Taxi'),
('Maruti Suzuki','Swift','Lxi'),
('Maruti Suzuki','Swift','Vxi'),
('Maruti Suzuki','Swift','Vxi Amt'),
('Maruti Suzuki','Swift','Zxi'),
('Maruti Suzuki','Swift','Zxi Amt'),
('Maruti Suzuki','Swift','Zxi Plus'),
('Maruti Suzuki','Swift','Ldi'),
('Maruti Suzuki','Swift','Vdi'),
('Maruti Suzuki','Swift','Vdi Amt'),
('Maruti Suzuki','Swift','Zdi'),
('Maruti Suzuki','Swift','Zdi Amt'),
('Maruti Suzuki','Swift','Zdi Plus'),
('Maruti Suzuki','Swift','Zxi Plus Amt'),
('Maruti Suzuki','Swift','Zdi Plus Amt'),
('Tata','Altroz','Xe Petrol'),
('Tata','Altroz','Xm Petrol'),
('Tata','Altroz','Xt Petrol'),
('Tata','Altroz','Xz Petrol'),
('Tata','Altroz','Xz (O) Petrol'),
('Tata','Altroz','Xe Diesel'),
('Tata','Altroz','Xm Diesel'),
('Tata','Altroz','Xt Diesel'),
('Tata','Altroz','Xz Diesel'),
('Tata','Altroz','Xz (O) Diesel'),
('ICML','Extreme','Ld Di Non Ac 9 Seater Bsiii'),
('ICML','Extreme','Ld Crdfi Non Ac 9 Seater Bsiv'),
('ICML','Extreme','Ld Di Ps Ac 9 Seater Bsiii'),
('ICML','Extreme','Ld Crdfi Ps Ac 9 Seater Bsiii'),
('ICML','Extreme','Sd Di 9 Seater Bsiii'),
('ICML','Extreme','Ld Crdfi Ps Ac 9 Seater Bsiv'),
('ICML','Extreme','Vd Crdfi 7 Seater Bsiii'),
('ICML','Extreme','Vd Di 7 Seater Bsiii'),
('ICML','Extreme','Sd Crdfi 9 Seater Bsiv'),
('ICML','Extreme','Vd Crdfi 7 Seater Bsiv'),
('ICML','Extreme','Sd Crdfi 9 Seater Bsiii'),
('Tata','Tigor','Revotron Xe'),
('Tata','Tigor','Revotron Xm'),
('Tata','Tigor','Revotron Xz'),
('Tata','Tigor','Revotron Xz Plus'),
('Tata','Tigor','Revotron Xma'),
('Tata','Tigor','Revotron Xza Plus'),
('Tata','Zest','Xe Petrol'),
('Tata','Zest','Xe Diesel'),
('Tata','Zest','Xm Petrol'),
('Tata','Zest','Xms Petrol'),
('Tata','Zest','Xt Petrol'),
('Tata','Zest','Xm Diesel'),
('Tata','Zest','Xms Diesel'),
('Tata','Zest','Xt Diesel'),
('Tata','Zest','Xma Diesel'),
('Tata','Zest','Xta Diesel'),
('Tata','Zest','Zest Premio Edition'),
('Honda','Amaze','S Cvt Petrol'),
('Honda','Amaze','E Mt Diesel'),
('Honda','Amaze','E Mt Petrol'),
('Honda','Amaze','S Cvt Diesel'),
('Honda','Amaze','V Cvt Petrol'),
('Honda','Amaze','V Cvt Diesel'),
('Honda','Amaze','S Mt Diesel'),
('Honda','Amaze','Vx Mt Diesel'),
('Honda','Amaze','V Mt Diesel'),
('Honda','Amaze','Vx Mt Petrol'),
('Honda','Amaze','V Mt Petrol'),
('Honda','Amaze','S Mt Petrol'),
('Honda','Amaze','Exclusive Edition Diesel'),
('Honda','Amaze','Exclusive Edition Petrol'),
('Honda','Amaze','Vx Cvt Diesel'),
('Honda','Amaze','Vx Cvt Petrol'),
('Honda','Amaze','Ace Edition Cvt Diesel'),
('Honda','Amaze','Ace Edition Cvt Petrol'),
('Honda','Amaze','Ace Edition Mt Diesel'),
('Honda','Amaze','Ace Edition Mt Petrol'),
('Maruti Suzuki','Gypsy','Hard Top'),
('Maruti Suzuki','Gypsy','Soft Top'),
('Hyundai','Venue','1.2 Kappa Mt E'),
('Hyundai','Venue','1.0 Turbo Gdi Mt S'),
('Hyundai','Venue','1.4 Crdi Mt E'),
('Hyundai','Venue','1.0 Turbo Gdi Mt Sx'),
('Hyundai','Venue','1.0 Turbo Gdi Mt Sx Dual Tone'),
('Hyundai','Venue','1.0 Turbo Gdi Mt Sx(O)'),
('Hyundai','Venue','1.0 Turbo Gdi Dct S'),
('Hyundai','Venue','1.0 Turbo Gdi Dct Sx Plus'),
('Hyundai','Venue','1.2 Kappa Mt S'),
('Hyundai','Venue','1.4 Crdi Mt S'),
('Hyundai','Venue','1.4 Crdi Mt Sx'),
('Hyundai','Venue','1.4 Crdi Mt Sx Dual Tone'),
('Hyundai','Venue','1.4 Crdi Mt Sx(O)'),
('Tata','Nexon','Xe'),
('Tata','Nexon','Xm'),
('Tata','Nexon','Xz'),
('Tata','Nexon','Xz Plus'),
('Tata','Nexon','Xz Plus Dual Tone'),
('Tata','Nexon','Xz Plus (O)'),
('Tata','Nexon','Xz Plus (O) Dual Tone'),
('Tata','Nexon','Xma'),
('Tata','Nexon','Xza Plus'),
('Tata','Nexon','Xza Plus Dual Tone'),
('Tata','Nexon','Xza Plus (O)'),
('Tata','Nexon','Xza Plus (O) Dual Tone'),
('Tata','Nexon','Xe Diesel'),
('Tata','Nexon','Xm Diesel'),
('Tata','Nexon','Xz Diesel'),
('Tata','Nexon','Xz Plus Diesel'),
('Tata','Nexon','Xz Plus Diesel Dual Tone'),
('Tata','Nexon','Xz Plus (O) Diesel'),
('Tata','Nexon','Xz Plus (O) Diesel Dual Tone'),
('Tata','Nexon','Xma Diesel'),
('Tata','Nexon','Xza Plus Diesel'),
('Tata','Nexon','Xza Plus Diesel Dual Tone'),
('Tata','Nexon','Xza Plus (O) Diesel'),
('Tata','Nexon','Xza Plus (O) Diesel Dual Tone'),
('Fiat','Linea','Active Fire'),
('Fiat','Linea','Active Multijet'),
('Fiat','Linea','Dynamic Multijet'),
('Fiat','Linea','Emotion Multijet'),
('Fiat','Linea','T-Jet Emotion'),
('Mahindra','Bolero Power Plus','Zlx'),
('Mahindra','Bolero Power Plus','Slx'),
('Mahindra','Bolero Power Plus','Sle'),
('Mahindra','Bolero Power Plus','Lx'),
('Mahindra','Bolero Power Plus','Plus Ac Bs4 Ps'),
('Mahindra','Bolero Power Plus','Plus Non Ac Bs4 Ps'),
('Maruti Suzuki','Vitara Brezza','Ldi'),
('Maruti Suzuki','Vitara Brezza','Vdi'),
('Maruti Suzuki','Vitara Brezza','Zdi'),
('Maruti Suzuki','Vitara Brezza','Zdi+'),
('Maruti Suzuki','Vitara Brezza','Zdi+ Dual Tone'),
('Maruti Suzuki','Vitara Brezza','Zdi+ Ags'),
('Maruti Suzuki','Vitara Brezza','Vdi Ags'),
('Maruti Suzuki','Vitara Brezza','Zdi Ags'),
('Maruti Suzuki','Vitara Brezza','Zdi+ Dual Tone Ags'),
('Hyundai','I20 Active','1.2 S'),
('Hyundai','I20 Active','1.2 Sx'),
('Hyundai','I20 Active','1.2 Sx Dual Tone'),
('Hyundai','I20 Active','1.4 Sx'),
('Ford','Ecosport','1.5L Ti-Vct Ambiente'),
('Ford','Ecosport','1.5L Ti-Vct Trend'),
('Ford','Ecosport','1.5L Ti-Vct Titanium'),
('Ford','Ecosport','1.5L Ti-Vct Titanium Plus At'),
('Ford','Ecosport','1.5L Tdci Ambiente'),
('Ford','Ecosport','1.5L Tdci Trend'),
('Ford','Ecosport','1.5L Tdci Titanium'),
('Ford','Ecosport','1.5L Tdci Titanium Plus'),
('Ford','Ecosport','1.5L Ti-Vct Titanium Plus'),
('Ford','Ecosport','1.5L Tdci Titanium S'),
('Ford','Ecosport','1.5L Ti-Vct Thunder Edition'),
('Ford','Ecosport','1.5L Tdci Thunder Edition'),
('Renault','Duster','Rxe Petrol'),
('Renault','Duster','Rxs Petrol'),
('Renault','Duster','Rxs (Opt) Cvt'),
('Renault','Duster','85 Ps Rxe Mt Diesel'),
('Renault','Duster','85 Ps Rxs Mt Diesel'),
('Renault','Duster','110 Ps Rxs Mt Diesel'),
('Renault','Duster','110 Ps Rxz Mt Diesel'),
('Renault','Duster','110 Ps Rxz Amt Diesel'),
('Renault','Duster','110 Ps Rxs Awd (Opt) Diesel'),
('Hyundai','Verna','1.6 Vtvt Sx'),
('Hyundai','Verna','1.6 Crdi Sx'),
('Hyundai','Verna','1.6 Crdi Sx (O)'),
('Hyundai','Verna','1.6 Vtvt Sx (O)'),
('Hyundai','Verna','1.6 Crdi Sx Plus At'),
('Hyundai','Verna','1.6 Vtvt Sx(O) At'),
('Hyundai','Verna','1.4 Vtvt Ex'),
('Hyundai','Verna','1.4 Vtvt E'),
('Hyundai','Verna','1.6 Vtvt Sx (O) Anniversary Edition'),
('Hyundai','Verna','1.6 Vtvt Sx Plus At'),
('Hyundai','Verna','1.6 Crdi Sx(O) At'),
('Hyundai','Verna','1.4 Crdi E'),
('Hyundai','Verna','1.4 Crdi Ex'),
('Mahindra','Xuv300','1.2 W4'),
('Mahindra','Xuv300','1.2 W6'),
('Mahindra','Xuv300','1.2 W8'),
('Mahindra','Xuv300','1.2 W8(O)'),
('Mahindra','Xuv300','1.5 W4'),
('Mahindra','Xuv300','1.5 W6'),
('Mahindra','Xuv300','1.5 W8'),
('Mahindra','Xuv300','1.5 W8 (O)'),
('Mahindra','Xuv300','1.5 W8 Amt'),
('Mahindra','Xuv300','1.5 W8 (O) Amt'),
('Mahindra','Xuv300','1.5 W6 Amt'),
('Renault','Lodgy','85 Ps Std'),
('Renault','Lodgy','85 Ps Rxe 8 Seater'),
('Renault','Lodgy','Stepway Rxz 110Ps 8-Seater'),
('Renault','Lodgy','Stepway Rxz 110Ps 7-Seater'),
('Renault','Lodgy','Stepway Rxl 85Ps 8-Seater'),
('Renault','Lodgy','Stepway Rxz 85Ps 8-Seater'),
('Renault','Lodgy','85 Ps Rxe 7 Seater'),
('Volkswagen','Vento','Trendline 1.6 (P)'),
('Volkswagen','Vento','Highline 1.6 (P)'),
('Volkswagen','Vento','Comfortline 1.6 (P)'),
('Volkswagen','Vento','Highline 1.2 (P) Dsg'),
('Volkswagen','Vento','Highline Plus 1.2 (P) Dsg'),
('Volkswagen','Vento','Trendline 1.5 (D)'),
('Volkswagen','Vento','Comfortline 1.5 (D)'),
('Volkswagen','Vento','Highline 1.5 (D)'),
('Volkswagen','Vento','Highline 1.5 (D) Dsg'),
('Volkswagen','Vento','Highline Plus 1.5 (D) Dsg'),
('Volkswagen','Vento','Gt Line (D)'),
('Volkswagen','Vento','Gt Line (P) Dsg'),
('Mahindra','E2O Plus','P4'),
('Mahindra','E2O Plus','P6'),
('Tata','Tigor Ev','Xm+'),
('Tata','Tigor Ev','Xt+'),
('Tata','Tigor Ev','Xe+'),
('Honda','Brv','E Petrol'),
('Honda','Brv','S Petrol'),
('Honda','Brv','V Petrol'),
('Honda','Brv','Vx Petrol'),
('Honda','Brv','V Cvt Petrol'),
('Honda','Brv','S Diesel'),
('Honda','Brv','V Diesel'),
('Honda','Brv','Vx Diesel'),
('Mahindra','Thar','Crde'),
('Mahindra','Thar','700 Special Edition'),
('Mahindra','Thar','Crde Abs'),
('Force','Gurkha','Xpedition 5 Door'),
('Force','Gurkha','Xplorer 3 Door'),
('Force','Gurkha','Xtreme'),
('Force','Gurkha','Xtreme Abs'),
('Force','Gurkha','Xpedition 3 Door'),
('Force','Gurkha','Xplorer 5 Door'),
('Maruti Suzuki','Xl6','Zeta Mt'),
('Maruti Suzuki','Xl6','Alpha Mt'),
('Maruti Suzuki','Xl6','Zeta At'),
('Maruti Suzuki','Xl6','Alpha At'),
('Fiat','Abarth Avventura','1.4 T-Jet'),
('Mahindra','Tuv300 Plus','P4'),
('Mahindra','Tuv300 Plus','P6'),
('Mahindra','Tuv300 Plus','P8'),
('Mahindra','Marazzo','M2 7 Str'),
('Mahindra','Marazzo','M4 7 Str'),
('Mahindra','Marazzo','M6 7 Str'),
('Mahindra','Marazzo','M8 7 Str'),
('Mahindra','Marazzo','M2 8 Str'),
('Mahindra','Marazzo','M4 8 Str'),
('Mahindra','Marazzo','M6 8 Str'),
('Mahindra','Marazzo','M8 8 Str'),
('Mahindra','Scorpio','S3 2Wd'),
('Mahindra','Scorpio','4Wd Getaway'),
('Mahindra','Scorpio','2Wd Getaway'),
('Mahindra','Scorpio','S5 2Wd'),
('Mahindra','Scorpio','S7 120 2Wd'),
('Mahindra','Scorpio','S7 140 2Wd'),
('Mahindra','Scorpio','S11 2Wd'),
('Mahindra','Scorpio','S11 4Wd'),
('Mahindra','Scorpio','S9 2Wd'),
('Skoda','Monte Carlo','Monte Carlo 1.5 Tdi At'),
('Skoda','Monte Carlo','Monte Carlo 1.6 Mpi At'),
('Skoda','Monte Carlo','Monte Carlo 1.5 Tdi Mt'),
('Skoda','Monte Carlo','Monte Carlo 1.6 Mpi Mt'),
('Mahindra','Xuv500','G At'),
('Mahindra','Xuv500','W7'),
('Mahindra','Xuv500','W7 At'),
('Mahindra','Xuv500','W9'),
('Mahindra','Xuv500','W9 At'),
('Mahindra','Xuv500','W11'),
('Mahindra','Xuv500','W11 At'),
('Mahindra','Xuv500','W11 (O)'),
('Mahindra','Xuv500','W11 (O) At'),
('Mahindra','Xuv500','G At'),
('Mahindra','Xuv500','W7'),
('Mahindra','Xuv500','W7 At'),
('Mahindra','Xuv500','W9'),
('Mahindra','Xuv500','W9 At'),
('Mahindra','Xuv500','W11'),
('Mahindra','Xuv500','W11 At'),
('Mahindra','Xuv500','W11 (O)'),
('Mahindra','Xuv500','W11 (O) At'),
('Mahindra','Xuv500','W11 (O) Awd'),
('Mahindra','Xuv500','W11 (O) Awd At'),
('Mahindra','Xuv500','W3'),
('Mahindra','E Verito','D4'),
('Mahindra','E Verito','D2'),
('Mahindra','E Verito','D6'),
('Tata','Hexa','Xm Plus 4X2'),
('Tata','Hexa','Xt 4X4'),
('Tata','Hexa','Xta 4X2'),
('Tata','Hexa','Xt 4X2'),
('Tata','Hexa','Xe 4X2'),
('Tata','Hexa','Xm 4X2'),
('Tata','Hexa','Xma 4X2'),
('Toyota','Innova Crysta','2.4 Gx 7 Str'),
('Toyota','Innova Crysta','2.4 Vx 7 Str'),
('Toyota','Innova Crysta','2.4 Gx 8 Str'),
('Toyota','Innova Crysta','2.4 Vx 8 Str'),
('Toyota','Innova Crysta','2.4 Zx 7 Str'),
('Toyota','Innova Crysta','2.7 Gx At 8 Str'),
('Toyota','Innova Crysta','2.7 Gx At 7 Str'),
('Toyota','Innova Crysta','2.7 Zx At 7 Str'),
('Toyota','Innova Crysta','2.7 Vx 7 Str'),
('Toyota','Innova Crysta','2.7 Gx Mt 7 Str'),
('Toyota','Innova Crysta','2.7 Gx Mt 8 Str'),
('Toyota','Innova Crysta','Touring Sport 2.4 Vx 7 Str'),
('Toyota','Innova Crysta','Touring Sport 2.7 Vx 7 Str'),
('Toyota','Innova Crysta','Touring Sport 2.7 Zx At 7 Str'),
('Toyota','Innova Crysta','2.4 G Plus 7 Str'),
('Toyota','Innova Crysta','2.4 G Plus 8 Str'),
('Jeep','Compass','1.4 Limited At'),
('Jeep','Compass','1.4 Sport'),
('Jeep','Compass','1.4 Limited (O) At'),
('Jeep','Compass','2.0 Sport'),
('Jeep','Compass','2.0 Longitude'),
('Jeep','Compass','2.0 Longitude (O)'),
('Jeep','Compass','2.0 Limited'),
('Jeep','Compass','2.0 Limited (O)'),
('Jeep','Compass','2.0 Limited 4X4'),
('Jeep','Compass','2.0 Limited (O) 4X4'),
('Jeep','Compass','1.4 Limited Plus At Petrol'),
('Jeep','Compass','2.0 Limited Plus 4X2 Diesel'),
('Jeep','Compass','2.0 Limited Plus 4X4 Diesel'),
('Jeep','Compass','2.0 Sport Plus'),
('Jeep','Compass','1.4 Sport Plus'),
('Jeep','Compass','1.4 Longitude (O) At'),
('Jeep','Compass','1.4 Limited (O) At Petrol Black Pack'),
('Jeep','Compass','2.0 Limited (O) Black Pack'),
('Jeep','Compass','2.0 Limited (O) 4X4 Black Pack'),
('Jeep','Compass','2.0 Limited Plus 4X4 At'),
('Jeep','Compass','2.0 Longitude 4X4 At'),
('Toyota','Corolla Altis','G Petrol'),
('Toyota','Corolla Altis','G At Petrol'),
('Toyota','Corolla Altis','Gl Petrol'),
('Toyota','Corolla Altis','Gl Diesel'),
('Toyota','Corolla Altis','G Diesel'),
('Toyota','Corolla Altis','Vl At Petrol'),
('Honda','Civic','1.8 V Cvt'),
('Honda','Civic','1.8 Vx Cvt'),
('Honda','Civic','1.8 Zx Cvt'),
('Honda','Civic','1.6 Vx Mt'),
('Honda','Civic','1.6 Zx Mt'),
('MG','Zs Ev','Excite'),
('MG','Zs Ev','Exclusive'),
('Kia','Carnival','Premium 7 Str'),
('Kia','Carnival','Premium 8 Str'),
('Kia','Carnival','Prestige 7 Str'),
('Kia','Carnival','Prestige 9 (6+3) Str'),
('Kia','Carnival','Limousine 7 Str'),
('Skoda','Superb','Style 1.8 Tsi Mt'),
('Skoda','Superb','Style 1.8 Tsi At'),
('Skoda','Superb','L & K 1.8 Tsi At'),
('Skoda','Superb','L & K 2.0 Tdi At'),
('Skoda','Superb','Style 2.0 Tdi At'),
('Skoda','Superb','Corporate Edition 1.8 Tsi At'),
('Skoda','Superb','Corporate Edition 2.0 Tdi At'),
('Volvo','V40','Kinetic'),
('Volvo','V40','R Design'),
('Toyota','Fortuner','2.8 4X2 At'),
('Toyota','Fortuner','2.8 4X2 Mt'),
('Toyota','Fortuner','2.8 4X4 Mt'),
('Toyota','Fortuner','2.8 4X4 At'),
('Toyota','Fortuner','2.7 4X2 At'),
('Toyota','Fortuner','2.7 4X2 Mt'),
('Toyota','Fortuner','Trd Celebratory Edition'),
('Ford','Endeavour','3.2L 4X4 At Titanium Plus'),
('Ford','Endeavour','2.2L 4X2 At Titanium Plus'),
('Ford','Endeavour','2.2L 4X2 Mt Titanium'),
('Mini','Cooper 3 Door','Cooper D'),
('Mini','Cooper 3 Door','Cooper S'),
('Skoda','Kodiaq Scout','2.0 Tdi At'),
('BMW','X1','Sdrive20D Expedition'),
('BMW','X1','Sdrive20D Xline'),
('BMW','X1','Xdrive20D M Sport'),
('BMW','X1','Sdrive20D M Sport'),
('BMW','X1','Sdrive20I Xline'),
('Volvo','S60','Polestar'),
('Volvo','S60','Momentum'),
('BMW','3-Series','320D Sport'),
('BMW','3-Series','320D Luxury Line'),
('BMW','3-Series','330I M Sport'),
('Volvo','S60 Cross Country','D4'),
('Audi','Q5','35 Tdi Premium Plus'),
('Audi','Q5','35 Tdi Technology'),
('Audi','Q5','45 Tfsi Premium Plus'),
('Audi','Q5','45 Tfsi Technology'),
('Land Rover','Range Evoque','S'),
('Land Rover','Range Evoque','Se R-Dynamic'),
('Land Rover','Range Evoque','S Petrol'),
('Land Rover','Range Evoque','Se R-Dynamic Petrol'),
('Volvo','Xc60','Inscription D5'),
('BMW','X4','Xdrive20D M Sport X'),
('BMW','X4','Xdrive30D M Sport X'),
('BMW','X4','Xdrive30I M Sport X'),
('Jeep','Wrangler','Unlimited'),
('BMW','Z4 Roadster','Sdrive 20I'),
('BMW','Z4 Roadster','M 40I'),
('Audi','Q7','45 Tdi Premium Plus'),
('Audi','Q7','45 Tdi Technology Pack'),
('Audi','Q7','40 Tfsi Quattro Premium Plus'),
('Audi','Q7','40 Tfsi Quattro Technology Pack'),
('Audi','Q7','45 Tdi Black Styling'),
('Audi','Q7','40 Tfsi Quattro Black Styling'),
('Land Rover','Range Evoque Convertible','2.0 Hse Dynamic'),
('Land Rover','Range Velar','2.0 Diesel R-Dynamic S'),
('Land Rover','Range Velar','2.0 Petrol R-Dynamic S'),
('Volvo','Xc90','D5 Inscription'),
('Volvo','Xc90','D5 Momentum'),
('Volvo','Xc90','T8 Excellence'),
('Volvo','Xc90','T8 Inscription'),
('Volvo','Xc90','D5 R-Design'),
('Land Rover','Range Sport','5.0L V8 Svr Petrol'),
('Land Rover','Range Sport','2.0L S Petrol'),
('Land Rover','Range Sport','2.0L Se Petrol'),
('Land Rover','Range Sport','3.0L V6 Se Petrol'),
('Land Rover','Range Sport','2.0L Hse Petrol'),
('Land Rover','Range Sport','3.0L V6 Hse Petrol'),
('Land Rover','Range Sport','5.0L V8 Autobiography Dynamic Petrol'),
('Land Rover','Range Sport','3.0L Tdv6 S Diesel'),
('Land Rover','Range Sport','3.0L Tdv6 Se Diesel'),
('Land Rover','Range Sport','4.4L Sdv8 Hse Diesel'),
('Jaguar','Xj','3.0L'),
('Jaguar','Xj','3.0L Portfolio'),
('Jaguar','Xj','50'),
('Porsche','Cayenne','E-Hybrid'),
('Porsche','Cayenne','Turbo'),
('Porsche','Cayenne','Base'),
('Maserati','Ghibli','Diesel'),
('Maserati','Ghibli','Gransport'),
('Maserati','Ghibli','Granlusso'),
('Toyota','Land Cruiser','Vx'),
('Audi','Rs7','Sportback'),
('Land Rover','Range','5.0L V8 Autobiography Petrol'),
('Land Rover','Range','5.0L V8 Svautobiography Dynamic Petrol'),
('Land Rover','Range','3.0L V6 Vogue Lwb Petrol'),
('Land Rover','Range','5.0L V8 Svautobiography Lwb Petrol'),
('Land Rover','Range','3.0L Tdv6 Vogue Diesel'),
('Land Rover','Range','3.0L Tdv6 Vogue Lwb Diesel'),
('Land Rover','Range','4.4L Sdv8 Autobiography Lwb Diesel'),
('Land Rover','Range','4.4L Sdv8 Svautobiography Lwb Diesel'),
('Land Rover','Range','4.4L Sdv8 Vogue Se Lwb Diesel'),
('Land Rover','Range','3.0L V6 Vogue Se Lwb Petrol'),
('Maserati','Grancabrio','Standard'),
('Lamborghini','Huracan','Lp 610-4'),
('Lamborghini','Huracan','Lp 580-2'),
('Lamborghini','Huracan','Avio'),
('Lamborghini','Huracan','Performante'),
('Lamborghini','Huracan','Lp 580-2 Spyder'),
('Lamborghini','Huracan','Lp 610-4 Spyder'),
('Lamborghini','Huracan','Evo'),
('Lamborghini','Huracan','Evo Spyder'),
('Lamborghini','Huracan','Evo Rwd'),
('Ferrari','488 Gtb','Std'),
('Ferrari','488 Gtb','Spider'),
('Ferrari','Gtc4 Lusso','V8 T'),
('Ferrari','Gtc4 Lusso','V12'),
('Lamborghini','Aventador','Lp 700-4'),
('Lamborghini','Aventador','Lp700-4 Roadster'),
('Lamborghini','Aventador','S'),
('Maruti Suzuki','Omni','5 Str Bs-Iv'),
('Maruti Suzuki','Omni','E 8 Str Bs-Iv'),
('Fiat','Punto Evo Pure','1.2L Fire Dynamic'),
('Fiat','Punto Evo Pure','1.3'),
('Ford','Figo','Ambiente 1.2 Ti-Vct'),
('Ford','Figo','Ambiente 1.5 Tdci'),
('Ford','Figo','Titanium 1.2 Ti-Vct'),
('Ford','Figo','Titanium1.5 Tdci'),
('Ford','Figo','Titanium Blu 1.2 Ti-Vct'),
('Ford','Figo','Titanium Blu 1.5 Tdci'),
('Maruti Suzuki','Baleno','1.3 Delta'),
('Maruti Suzuki','Baleno','1.3 Alpha'),
('Maruti Suzuki','Baleno','1.3 Sigma'),
('Maruti Suzuki','Baleno','1.3 Zeta'),
('Maruti Suzuki','Baleno','1.2 Alpha'),
('Maruti Suzuki','Baleno','1.2 Alpha Cvt'),
('Maruti Suzuki','Baleno','1.2 Delta'),
('Maruti Suzuki','Baleno','1.2 Delta Cvt'),
('Maruti Suzuki','Baleno','1.2 Sigma'),
('Maruti Suzuki','Baleno','1.2 Zeta'),
('Maruti Suzuki','Baleno','1.2 Delta Dualjet'),
('Maruti Suzuki','Baleno','1.2 Zeta Dualjet'),
('Maruti Suzuki','Baleno','1.2 Zeta Cvt'),
('Hyundai','Grand I10','1.2 Kappa Vtvt Magna'),
('Hyundai','Grand I10','1.2 Kappa Vtvt Sportz'),
('Hyundai','Grand I10','1.2 Kappa Vtvt Magna At'),
('Hyundai','Grand I10','1.2 Kappa Vtvt Sportz At'),
('Hyundai','Grand I10','1.2 Kappa Vtvt Sportz Dual Tone'),
('Hyundai','Grand I10','1.2 Kappa Vtvt Magna Cng'),
('Fiat','Linea Classic','1.3 Multijet'),
('Fiat','Linea Classic','1.4'),
('Fiat','Linea Classic','Plus 1.3 Multijet'),
('Nissan','Sunny','Xe Petrol'),
('Nissan','Sunny','Xl Petrol'),
('Nissan','Sunny','Xl Diesel'),
('Nissan','Sunny','Xv Diesel'),
('Nissan','Sunny','Xe Diesel'),
('Nissan','Sunny','Xv Cvt'),
('Nissan','Sunny','Special Edition Diesel'),
('Maruti Suzuki','Ertiga','Lxi'),
('Maruti Suzuki','Ertiga','Zxi'),
('Maruti Suzuki','Ertiga','Vxi At'),
('Maruti Suzuki','Ertiga','Zxi Plus'),
('Maruti Suzuki','Ertiga','Vxi'),
('Maruti Suzuki','Ertiga','Zxi At'),
('Maruti Suzuki','Ertiga','1.5L Vdi'),
('Maruti Suzuki','Ertiga','1.5L Zdi'),
('Maruti Suzuki','Ertiga','1.5L Zdi Plus'),
('Maruti Suzuki','Ertiga','Vxi Cng (Cng +'),
('Maruti Suzuki','Baleno Rs','Rs 1.0'),
('Honda','Wr-V','Vx Diesel'),
('Honda','Wr-V','Vx Petrol'),
('Honda','Wr-V','S Diesel'),
('Honda','Wr-V','S Petrol'),
('Honda','Wr-V','Edge Plus Edition Diesel'),
('Honda','Wr-V','Edge Plus Edition Petrol'),
('Honda','Wr-V','Exclusive Edition Diesel'),
('Honda','Wr-V','Exclusive Edition Petrol'),
('Honda','Wr-V','V Diesel'),
('Mahindra','Tuv300','T4 Plus'),
('Mahindra','Tuv300','T6 Plus'),
('Mahindra','Tuv300','T8'),
('Mahindra','Tuv300','T10'),
('Mahindra','Tuv300','T10 (O)'),
('Mahindra','Tuv300','T10 Dual Tone'),
('Mahindra','Tuv300','T10 (O) Dual Tone'),
('Maruti Suzuki','S-Cross','1.3L Sigma'),
('Maruti Suzuki','S-Cross','1.3L Delta'),
('Maruti Suzuki','S-Cross','1.3L Zeta'),
('Maruti Suzuki','S-Cross','1.3L Alpha'),
('Renault','Captur','Rxe Petrol'),
('Renault','Captur','Rxe Diesel'),
('Renault','Captur','Platine Diesel Dual Tone'),
('Renault','Captur','Platine Petrol Dual Tone'),
('Mahindra','Xylo','D2 Bs-Iv'),
('Mahindra','Xylo','D4 Bs-Iv'),
('Mahindra','Xylo','H4 Bs-Iv'),
('Mahindra','Xylo','H4 Abs Bs-Iv'),
('Mahindra','Xylo','H8 Abs Airbags Bs-Iv'),
('Kia','Seltos','Hte 1.5'),
('Kia','Seltos','Htk 1.5'),
('Kia','Seltos','Htk Plus 1.5'),
('Kia','Seltos','Htx 1.5'),
('Kia','Seltos','Htx Cvt 1.5'),
('Kia','Seltos','Hte 1.5 Diesel'),
('Kia','Seltos','Htk 1.5 Diesel'),
('Kia','Seltos','Htk Plus 1.5 Diesel'),
('Kia','Seltos','Htk Plus At 1.5 Diesel'),
('Kia','Seltos','Htx Plus 1.5 Diesel'),
('Kia','Seltos','Htx Plus At 1.5 Diesel'),
('Kia','Seltos','Gtk 1.4'),
('Kia','Seltos','Gtx 1.4'),
('Kia','Seltos','Gtx At 1.4'),
('Kia','Seltos','Gtx Plus 1.4'),
('Kia','Seltos','Htx 1.5 Diesel'),
('Nissan','Terrano','Xe D 85Ps'),
('Nissan','Terrano','Xv D Premium 110 Ps Amt'),
('Nissan','Terrano','Xl (P)'),
('Nissan','Terrano','Xl D(O)'),
('Nissan','Terrano','Xv D Premium 110 Ps'),
('Nissan','Terrano','Sport Edition'),
('Tata','Safari Storme','2.2 Lx 4X2'),
('Tata','Safari Storme','2.2 Ex 4X2'),
('Tata','Safari Storme','2.2 Vx 4X2 Varicor 400'),
('Tata','Safari Storme','2.2 Vx 4X4 Varicor 400'),
('MG','Hector','1.5L Style'),
('MG','Hector','2.0L Style'),
('MG','Hector','2.0L Super'),
('MG','Hector','2.0L Smart'),
('MG','Hector','2.0L Sharp'),
('MG','Hector','1.5L Super'),
('MG','Hector','1.5L Super Hybrid'),
('MG','Hector','1.5L Sharp Hybrid'),
('MG','Hector','1.5L Smart Hybrid'),
('MG','Hector','1.5L Smart Dct'),
('MG','Hector','1.5L Sharp Dct'),
('Tata','Nexon Ev','Xm'),
('Tata','Nexon Ev','Xz Plus'),
('Tata','Nexon Ev','Xz Plus Lux'),
('Hyundai','Elantra','S'),
('Hyundai','Elantra','Sx'),
('Hyundai','Elantra','Sx At'),
('Hyundai','Elantra','Sx(O) At'),
('Hyundai','Tucson','2Wd Mt Diesel'),
('Hyundai','Tucson','2Wd Mt Petrol'),
('Hyundai','Tucson','2Wd At Gl Diesel'),
('Hyundai','Tucson','2Wd At Gl Petrol'),
('Hyundai','Tucson','4Wd At Gls Diesel'),
('Hyundai','Tucson','2Wd At Gls Petrol'),
('Hyundai','Tucson','2Wd At Gl(O) Petrol'),
('Hyundai','Tucson','2Wd At Gl(O) Diesel'),
('Volkswagen','Passat','2.0 Tdi Comfortline'),
('Volkswagen','Passat','2.0 Tdi Highline'),
('Volkswagen','Passat','2.0 Tdi Comfortline Connect'),
('Volkswagen','Passat','2.0 Tdi Highline Connect'),
('Volvo','V40 Cross Country','D3'),
('Volvo','V40 Cross Country','T4'),
('Mini','Countryman','Cooper S'),
('Mini','Countryman','Cooper Sd'),
('Mini','Countryman','Cooper S Jcw Inspired'),
('Mini','Countryman','Black Edition'),
('Toyota','Prius','Z8'),
('Lexus','Es','300H'),
('Lexus','Nx 300H','F-Sport'),
('Lexus','Nx 300H','Luxury'),
('Jaguar','F-Pace','Prestige'),
('Jaguar','F-Pace','Prestige Petrol'),
('Volvo','V90 Cross Country','D5 Inscription'),
('Audi','A5 Cabriolet','2.0 Tdi'),
('BMW','X7','Xdrive 40I'),
('BMW','X7','Xdrive30D Dpe Signature'),
('BMW','M4','Coupe'),
('Porsche','911','Carrera S'),
('Porsche','911','Carrera S Cabriolet'),
('Nissan','Gtr','3.8 V6'),
('Aston Martin','Vantage','Coupe'),
('Aston Martin','Rapide','Luxe'),
('Ferrari','812 Superfast','Superfast'),
('Maruti Suzuki','Alto 800 Tour','H1'),
('Maruti Suzuki','Alto 800 Tour','H1 (O)'),
('Hyundai','Grand I10 Nios','Magna 1.2 Crdi'),
('Hyundai','Grand I10 Nios','Era 1.2 Vtvt'),
('Hyundai','Grand I10 Nios','Magna 1.2 Vtvt'),
('Hyundai','Grand I10 Nios','Magna Amt 1.2 Vtvt'),
('Hyundai','Grand I10 Nios','Sportz 1.2 Vtvt'),
('Hyundai','Grand I10 Nios','Sportz Amt 1.2 Vtvt'),
('Hyundai','Grand I10 Nios','Sportz Dual Tone 1.2 Vtvt'),
('Hyundai','Grand I10 Nios','Asta 1.2 Vtvt'),
('Hyundai','Grand I10 Nios','Sportz Amt 1.2 Crdi'),
('Hyundai','Grand I10 Nios','Asta 1.2 Crdi'),
('Hyundai','Xcent','S 1.2'),
('Hyundai','Xcent','S At 1.2'),
('Hyundai','Xcent','Sx 1.2'),
('Hyundai','Xcent','Sx 1.2 (O)'),
('Hyundai','Xcent','S 1.2 Crdi'),
('Hyundai','Xcent','E'),
('Hyundai','Xcent','Sx 1.2 Crdi'),
('Hyundai','Xcent','Sx 1.2 Crdi (O)'),
('Hyundai','Xcent','E Crdi'),
('Nissan','Micra','Xl (O) Cvt'),
('Nissan','Micra','Xv Cvt'),
('Nissan','Micra','Xld (O)'),
('Nissan','Micra','Xvd'),
('Mahindra','Bolero','Zlx'),
('Mahindra','Bolero','Slx'),
('Mahindra','Bolero','Sle'),
('Mahindra','Bolero','Ex'),
('Mahindra','Bolero','Ex Non Ac'),
('Maruti Suzuki','Ciaz','1.3L Alpha Smart Hybrid'),
('Maruti Suzuki','Ciaz','1.3L Sigma Smart Hybrid'),
('Maruti Suzuki','Ciaz','1.3L Delta Smart Hybrid'),
('Maruti Suzuki','Ciaz','1.3L Zeta Smart Hybrid'),
('Maruti Suzuki','Ciaz','1.5L Sigma Smart Hybrid'),
('Maruti Suzuki','Ciaz','1.5L Delta Smart Hybrid'),
('Maruti Suzuki','Ciaz','1.5L Zeta Smart Hybrid'),
('Maruti Suzuki','Ciaz','1.5L Alpha Smart Hybrid'),
('Maruti Suzuki','Ciaz','1.5L Delta At Smart Hybrid'),
('Maruti Suzuki','Ciaz','1.5L Zeta At Smart Hybrid'),
('Maruti Suzuki','Ciaz','1.5L Alpha At Smart Hybrid'),
('Maruti Suzuki','Ciaz','1.5L Alpha'),
('Maruti Suzuki','Ciaz','1.5L Delta'),
('Maruti Suzuki','Ciaz','1.5L Zeta'),
('Skoda','Rapid','1.6 Mpi Ambition'),
('Skoda','Rapid','1.5 Tdi Cr Active'),
('Skoda','Rapid','1.6 Mpi Active'),
('Skoda','Rapid','1.5 Tdi Cr Ambition'),
('Skoda','Rapid','1.5 Tdi Cr Ambition At'),
('Skoda','Rapid','1.6 Mpi Style At'),
('Skoda','Rapid','1.5 Tdi Cr Style At'),
('Skoda','Rapid','1.5 Tdi Cr Style'),
('Skoda','Rapid','1.6 Mpi Style'),
('Skoda','Rapid','1.6 Mpi Ambition At'),
('Skoda','Rapid','Onyx Mt Petrol'),
('Skoda','Rapid','Onyx At Petrol'),
('Skoda','Rapid','Onyx Mt Diesel'),
('Skoda','Rapid','Onyx At Diesel'),
('Fiat','Abarth Punto','1.4 T-Jet'),
('Hyundai','Creta','1.4 Crdi E Plus'),
('Hyundai','Creta','1.6 Vtvt E Plus'),
('Hyundai','Creta','1.6 Vtvt Sx'),
('Hyundai','Creta','1.6 Vtvt Sx (O)'),
('Hyundai','Creta','1.6 Vtvt Sx At'),
('Hyundai','Creta','1.6 Vtvt Sx Dual Tone'),
('Hyundai','Creta','1.4 Crdi S'),
('Hyundai','Creta','1.6 Crdi Sx'),
('Hyundai','Creta','1.6 Crdi Sx (O)'),
('Hyundai','Creta','1.6 Crdi Sx At'),
('Hyundai','Creta','1.6 Crdi Sx Dual Tone'),
('Hyundai','Creta','1.6 Crdi S At'),
('Hyundai','Creta','1.6 Vtvt Sx (O) Executive'),
('Hyundai','Creta','1.6 Crdi Sx (O) Executive'),
('Hyundai','Creta','1.4 Crdi Ex'),
('Hyundai','Creta','1.6 Vtvt Ex'),
('Hyundai','Creta','Sports Edition Petrol'),
('Hyundai','Creta','Sports Edition Diesel'),
('Tata','Harrier','Revotorq Xe'),
('Tata','Harrier','Revotorq Xm'),
('Tata','Harrier','Revotorq Xt'),
('Tata','Harrier','Revotorq Xz'),
('Tata','Harrier','Revotorq Xz Dual Tone'),
('Tata','Harrier','Revotorq Dark Edition'),
('Isuzu','Dmax V-Cross','Standard'),
('Isuzu','Dmax V-Cross','High Z'),
('Isuzu','Dmax V-Cross','Z Prestige'),
('Mitsubishi','Outlander','2.4L Outlander'),
('Honda','Accord Hybrid','2.0 At'),
('BMW','5-Series','520D Luxury Line'),
('BMW','5-Series','530D M Sport'),
('BMW','5-Series','530I M Sport'),
('BMW','6-Series','630D Gt Luxury Line'),
('BMW','6-Series','630D Gt M Sport'),
('BMW','6-Series','630I Gt Luxury Line'),
('BMW','6-Series','620D Gt Luxury Line'),
('Porsche','Macan','S'),
('Porsche','Macan','Base'),
('Jaguar','F-Type','5.0 Convertible R'),
('Jaguar','F-Type','5.0 Coupe R'),
('Jaguar','F-Type','Svr Coupe'),
('Jaguar','F-Type','Svr Convertible'),
('Jaguar','F-Type','2.0L Coupe'),
('Jaguar','F-Type','2.0L Convertible'),
('Jaguar','F-Type','2.0 Convertible R Dynamic'),
('Jaguar','F-Type','2.0 Coupe R Dynamic'),
('BMW','M5','Competition'),
('Lexus','Lx 570','V8'),
('Ferrari','458 Spider','V8'),
('Maruti Suzuki','Wagon','Vxi'),
('Maruti Suzuki','Wagon','Vxi Ags'),
('Maruti Suzuki','Wagon','1.2L Zxi'),
('Maruti Suzuki','Wagon','Lxi'),
('Maruti Suzuki','Wagon','1.2L Vxi'),
('Maruti Suzuki','Wagon','1.2L Vxi Ags'),
('Maruti Suzuki','Wagon','1.2L Zxi Ags'),
('Maruti Suzuki','Wagon','Lxi (O)'),
('Maruti Suzuki','Wagon','Vxi (O)'),
('Maruti Suzuki','Wagon','1.2L Vxi (O)'),
('Maruti Suzuki','Wagon','1.2L Vxi Ags (O)'),
('Maruti Suzuki','Wagon','Vxi Ags (O)'),
('Maruti Suzuki','Wagon','Lxi Cng'),
('Maruti Suzuki','Wagon','Lxi (O) Cng'),
('Tata','Tiago Nrg','1.2L Revotron'),
('Tata','Tiago Nrg','1.05L Revotorq'),
('Tata','Tiago Nrg','1.2L Revotron Amt'),
('Mahindra','Nuvosport','N4'),
('Mahindra','Nuvosport','N6'),
('Mahindra','Nuvosport','N8'),
('Mahindra','Nuvosport','N4 +'),
('Mahindra','Nuvosport','N6 Amt'),
('Mahindra','Nuvosport','N8 Amt'),
('Nissan','Kicks','Xl Petrol'),
('Nissan','Kicks','Xv Petrol'),
('Nissan','Kicks','Xl Diesel'),
('Nissan','Kicks','Xv Diesel'),
('Nissan','Kicks','Xv Premium'),
('Nissan','Kicks','Xv Premium (O)'),
('Nissan','Kicks','Xv Premium (O) Dual Tone'),
('Nissan','Kicks','Xe Diesel'),
('Tata','Winger','15S'),
('Hyundai','Kona Electric','Premium'),
('Toyota','Camry','Hybrid'),
('Audi','A5','Sportback'),
('Land Rover','Discovery','3.0 Hse Diesel'),
('Land Rover','Discovery','3.0 Se Diesel'),
('Land Rover','Discovery','3.0 Hse Petrol'),
('Land Rover','Discovery','3.0 Se Petrol'),
('Land Rover','Discovery','3.0 S Diesel'),
('Land Rover','Discovery','3.0 S Petrol'),
('Land Rover','Discovery','3.0 Hse Luxury Diesel'),
('Land Rover','Discovery','3.0 Hse Luxury Petrol'),
('Lexus','Ls 500H','Luxury'),
('Lexus','Ls 500H','Ultra Luxury'),
('Lexus','Ls 500H','Distinct'),
('Fiat','Punto Evo','Dynamic 1.2'),
('Fiat','Punto Evo','Active Multijet 1.3'),
('Fiat','Punto Evo','Dynamic Multijet 1.3'),
('Fiat','Punto Evo','Emotion Multijet 1.3'),
('Toyota','Yaris','J'),
('Toyota','Yaris','G'),
('Toyota','Yaris','V'),
('Toyota','Yaris','Vx Cvt'),
('Toyota','Yaris','G Cvt'),
('Toyota','Yaris','J Cvt'),
('Toyota','Yaris','V Cvt'),
('Toyota','Yaris','Vx'),
('Toyota','Yaris','V (O)'),
('Toyota','Yaris','J (O)'),
('Toyota','Yaris','G (O)'),
('Toyota','Yaris','J (O) Cvt'),
('Toyota','Yaris','G (O) Cvt'),
('Toyota','Yaris','V (O) Cvt'),
('Skoda','Octavia','Ambition 1.4 Tsi'),
('Skoda','Octavia','Ambition 2.0 Tdi Cr'),
('Skoda','Octavia','Style 1.4 Tsi'),
('Skoda','Octavia','Style 1.8 Tsi At'),
('Skoda','Octavia','Style 2.0 Tdi Cr'),
('Skoda','Octavia','Style 2.0 Tdi Cr At'),
('Skoda','Octavia','L & K 1.8 Tsi At'),
('Skoda','Octavia','L & K 2.0 Tdi Cr At'),
('Skoda','Octavia','Corporate Edition 1.4 Tsi'),
('Skoda','Octavia','Corporate Edition 2.0 Tdi'),
('Skoda','Octavia','Onyx 1.8 Tsi Dsg'),
('Skoda','Octavia','Onyx 2.0 Tdi Dsg'),
('Porsche','Cayenne Coupe','Base'),
('Porsche','Cayenne Coupe','Turbo'),
('Mahindra','Verito','1.5 D2'),
('Mahindra','Verito','1.5 D4 Bs-Iv'),
('Mahindra','Verito','1.5 D6 Bs-Iv'),
('Mitsubishi','Pajero Sport','2.5 Mt'),
('Mitsubishi','Pajero Sport','2.5 At'),
('Mitsubishi','Pajero Sport','Limited Edition'),
('Mitsubishi','Pajero Sport','Select Plus Mt'),
('Mitsubishi','Pajero Sport','Select Plus At'),
('Bentley','Flying Spur','V8'),
('Bentley','Flying Spur','W12'),
('Honda','City','Sv Mt Petrol'),
('Honda','City','V Mt Petrol'),
('Honda','City','Vx Mt Petrol'),
('Honda','City','Vx Cvt Petrol'),
('Honda','City','Sv Mt Diesel'),
('Honda','City','V Mt Diesel'),
('Honda','City','Vx Mt Diesel'),
('Honda','City','Zx Mt Diesel'),
('Honda','City','Zx Cvt Petrol'),
('Honda','City','V Cvt Petrol'),
('Mitsubishi','Montero','3.2 At');
