CREATE TABLE IF NOT EXISTS loyalty (
  id          INT UNSIGNED   AUTO_INCREMENT PRIMARY KEY,
  customer_id INT UNSIGNED   NOT NULL,
  credits     DECIMAL(10,2)  NOT NULL DEFAULT 0.00,
  free_washes INT UNSIGNED   NOT NULL DEFAULT 0,
  wax_count   INT UNSIGNED   NOT NULL DEFAULT 0,
  updated_at  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_customer_id (customer_id),
  FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
